output   = "internal\\models"
wipe     = true
no-tests = true

[psql]
  dbname = "gamesparks_db"
  host   = "127.0.0.1"
  port   = 5432
  user   = "postgres"
  pass   = "12345"
  schema = "public"
  sslmode = "disable"
  blacklist = ["migrations"]